name: Update File List

on:
  push:
    branches:
      - main

jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate file list JSON
        run: |
          find files -type f | jq -R -s 'split("\n") | map(select(length > 0))' > filelist.json

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add filelist.json
          
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Automatically update filelist.json"
            git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
            git push
          fi
