name: Update File List

permissions:
  contents: write

on:
  push:
    branches:
      - main

jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate file list JSON
        run: |
          find files -type f | jq -R -s 'split("\n") | map(select(length > 0))' > filelist.json

      - name: Commit changes locally
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add filelist.json
          git diff --staged --quiet || git commit -m "Automatically update filelist.json"

      - name: Push changes
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: false
